### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'initializeMediaKeys')

### ISSUE THREAD

**Issue by techterbium** [videojs/videojs-contrib-dash#375]
## TypeError: Cannot read properties of undefined (reading 'initializeMediaKeys')

I am trying to play an encrypted .mpd content with clearkeys. I made sure that the keys are properly set as below

```
{
  "src": "/Users/user/videos/first/01krishna.asar/stream.mpd",
  "type": "application/dash+xml",
  "keySystemOptions": [
    {
      "name": "org.w3.clearkey",
      "options": {
        "clearkeys": {
          "m3b4JiWfBUnx3XuDCb5d4j": "tUHZFq5wPvS9Xx3e5XHeLS"
        }
      }
    }
  ]
}
```

However, I am seeing the below error when loading the video.  Can anybody help me understand what is going wrong here?
Much thanks in advance. 

### Expected
Expect to play the .mpd file 

### Actual
Error is thrown

### Error output
```
video.es.js:228 VIDEOJS: ERROR: TypeError: Cannot read properties of undefined (reading 'initializeMediaKeys')
    at tc (video.es.js:54099:19)
    at t.n.createKeySessions_ (video.es.js:54850:5)
    at t.n.handleWaitingForKey_ (video.es.js:54879:10)
    at HTMLVideoElement.r.dispatcher.r.dispatcher (video.es.js:2311:31)
```

## Additional Information
Please include any additional information necessary here. Including the following:

#### videojs
what version of videojs does this occur with?
    "video.js": "^7.20.2",
    "videojs-contrib-dash": "^5.1.1",
    "dashjs": "^4.4.1",

#### browsers
Electron (Chrome)

#### OSes
what platforms (operating systems and devices) are affected?
mac

### plugins
are any videojs plugins being used on the page? If so, please list them below.
- overlay

**Comment by damanV5** [comment]
@techterbium Any update on this?
